# Generated by Django 5.2.5 on 2025-09-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vegetable',
            new_name='Recipes',
        ),
    ]
