# Generated by Django 5.2.5 on 2025-09-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0003_recipes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='user',
        ),
    ]
