# Generated by Django 5.2.5 on 2025-09-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0004_remove_recipes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
