# Generated by Django 5.2.5 on 2025-09-09 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0003_subjects_studentmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_report_card', models.DateField(auto_created=True)),
                ('student_rank', models.IntegerField()),
                ('remarks', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportcard', to='management_app.students')),
            ],
            options={
                'verbose_name': 'Report Card',
            },
        ),
    ]
