# Generated by Django 5.2.5 on 2025-09-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0004_reportcards'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcards',
            unique_together={('student_rank', 'date_of_report_card')},
        ),
        migrations.RemoveField(
            model_name='reportcards',
            name='remarks',
        ),
    ]
