# Generated by Django 5.2.5 on 2025-09-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0005_alter_reportcards_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcards',
            name='date_of_report_card',
            field=models.DateField(auto_now_add=True),
        ),
    ]
