# Generated by Django 5.2.5 on 2025-09-09 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0006_alter_reportcards_date_of_report_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcards',
            options={'ordering': ['student_rank'], 'verbose_name': 'Report Card'},
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentmarks', to='management_app.students'),
        ),
    ]
