# Generated by Django 5.2.5 on 2025-09-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0007_alter_reportcards_options_alter_studentmarks_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
